<p><i>Blasphemy and heresy.</p>

<p>George Downs, senior elder of The American Church of the New Christ, reviewed the charges against Ann Burton, a troublesome sophomore at the church’s local college whose antics had finally gone too far. He took a moment to glance over a copy of the Seattle counterculture paper that had just published Ann’s essay – an essay that put her in the company of the worst of the faith’s growing number of critics. A look of contempt came over his face as he concluded that this so-called counterculture rubbish had no culture at all.</p>

<p>Downs had spent the past several days in prayer and contemplation regarding the Burton matter. During that time his emotions ranged from the sadness and disappointment a parent feels when a child goes astray to the fire and brimstone outrage of a religious zealot. Today Ann would come to trial before church leaders and, his patience spent, Downs was determined that she be shown no mercy. We’ve done all we can to set things right, Downs concluded, but this was the third time in less than a year that he and others had been required to deal with Ann’s defiance and conniving.</p>

<p>. . .</p>

<p>“No, Ann,” he muttered to himself, “you’ve gone too far this time. You have publicly humiliated the faith and its leadership. The book of Jeremiah tells us that ‘Thou shalt die, because thou hast taught rebellion against the Lord’. We may not be able to bring you an earthly death, but we can condemn your soul to eternal damnation. You will be excommunicated and shunned. There will be no place for you in our society. The church succeeds or fails on obedience to authority and conformity to its culture. Today we will be done with you. With God as my witness, the nail that stands will be hammered down.”</i></p>

<a href="http://www.amazon.com/Dark-Deception-Mr-Lawrence-Pratt/dp/1481899376"><img class="floatleft" width="300" height="480" src="books/dd/cover_med.png"/></a><p>And so begins <a href="http://www.amazon.com/Dark-Deception-Mr-Lawrence-Pratt/dp/1481899376">Dark Deception</a> and its journey into the world of The American Church of the New Christ.</p>

<p>*   *  *</p>

<p>Dark Deception is an emotionally engaging and thought provoking work that centers around an independent college woman and a closely-knit trio of women who are part of an authoritarian, faith-based community that constantly attempts to compromise their individuality. The former individual serves as a dynamic catalyst for the book while the latter group anchors the text as they come to depend on one another in their attempts to live meaningful lives in a restrictive environment. The impact of families, friends, and others in the community on our protagonists present forces that don't always work in harmony in a culture that all but dictates harmonious conformity – or, at least, the appearance of such. The lives of these women and other characters – major and minor – unfold in a tapestry of emotions and relationships as all attempt to deal with the demands of an intolerant faith and its restrictive dogma. The book's characters – both within and outside the faith – meld and collide in a series of encounters that involve family, love, betrayal, and a quest for power and control.</p>

<p>*   *  *</p>

<p>While Dark Deception is not directly about the LDS church and its culture, the book is based on and influenced by the seven years’ experience the author and his wife, Mikayla, encountered as an adult LDS converts-to-apostates some thirty years ago. Without the family’s membership in the LDS church, the book would not exist. A fictional faith was decided upon in order to provide a more creative environment in which Pratt could address not only issues with the LDS church but with authority and authoritarian institutions in general.  <a href="http://mainstreetplaza.com/2013/07/13/the-dangers-of-obedience-lawrence-pratts-dark-deception/">Read</a> <a href="http://youngmormonfeminists.org/2013/02/13/book-recommendation-dark-deception-by-lawrence-pratt/">more</a>!</p>
