<p>Brought up in a religious home, Sophia believes the only way to have a forever family is by following church leaders and obediently choosing the right. She goes to the right school, marries the right man in the right place, and does the right thing by staying home to raise her children. But when she starts asking questions about grace, love, and the nature of God, she realizes her spiritual struggles could rip her family apart.</p>
<a href="http://www.goodreads.com/book/show/15839551-mormon-diaries"><img class="floatleft" width="295" height="475" src="books/md/cover_med.png"/></a><p><i>And so, when the prayer ended and I felt nothing but the air around me, I convinced myself I’d felt something the same way a child who believes in Santa runs through the house on Christmas Eve announcing they’ve seen flying reindeer.</p>
</p>I stood and said, “I feel it!”</p>
</p>But in the moments that followed, when people were shaking my hand and there was no time for confession, regret washed over me.</p>
</p>I had lied.</p>
</p>So on the day after my baptism and confirmation, I sat in Fast & Testimony Meeting while people got up one by one and said, “I’d like to bear my testimony that I know the church is true. I know Joseph Smith was a prophet and that we have the one pure Gospel of Jesus Christ.”</p>
</p>Many of them told stories about their family, some recounted experiences when they’d felt the spirit. But when one man in particular spoke about my baptism and confirmation, saying how my countenance had glowed when I stood and said, “I feel it!” my stomach twisted with guilt.</p>
</p>“I didn’t really feel anything,” I whispered to my dad. “Should I go up and tell everyone the truth?”</p>
</p>I’d been taught all my life to be honest, and my impulse to go up to the pulpit and confess my sin was almost unbearable. I could, in fact, think of nothing more important than correcting the lie I’d told.</p>
</p>My father, however, knew people better than I did. He knew perfectly well what was appropriate in a Sunday service. He knew what I did not, that there’d been conflict amongst some in the congregation over what kinds of stories were appropriate to tell in church. So while I had no idea what was going through his mind at that moment, I’m sure what he said next was his way of looking out for me.</p>
</p>“Don’t do that, sweetheart. You wouldn’t want to hurt anyone’s testimony.”</i> <a href="https://mainstreetplaza.com/2012/11/28/hurting-relationships-sophia-l-stones-mormon-diaries/"><b>Read more</b></a></p>
