<p><a href="https://www.amazon.com/American-Trinity-Stories-Mormon-Corridor/dp/1961471027"><i>American Trinity and other Stories from the Mormon Corridor</i></a> by author David G. Pace is a collection of twelve stories that span the Mormon Corridor—a geographical as well as, now, globally psychic space inhabited by America's most "successful" indigenous religion. At times rendered through life's daily grind (politics, marriage, acquiring an STD... and too many parking tickets), other times through the supernatural and fabulist (angels and personified names of the dead ripped from the real-life Utah mountain vault filled with genealogical records), these are Latter-day Saints who see things “Mormonly” (with apologies to “New Englandly” Emily Dickinson) both driven and riven by their frenetic and sacralized sense of community, their orthodoxy, their doubts and their awkward (often futile) rebellions to comical, poignant, sometimes harrowing ends.</p>
<a href="https://www.amazon.com/American-Trinity-Stories-Mormon-Corridor/dp/1961471027"><img class="floatleft" width="300" height="457" src="books/at/cover_med.png"/></a><p>The title story “American Trinity” won the 2011 award for best short story by the Association of Mormon Letters, and best short story for 2011 by Dialogue Journal which first published the story, Pace’s first. In the book’s foreword by University of Utah professor Christopher T. Lewis places the collection in the context of Mormon literature with the throughline of the “Three Nephites” folklore stories often shared by Latter-day Saints: These stories, he writes, "convey the longing of those who are in some sense out of communion: lonesome, solemn, wandering, cast out, unrecognized by the Church or their own people. But they need not
worry that there is no book that—transcending orthodoxy and disbelief—captures enough in-between-ness to find themselves in. David G. Pace has written it. That’s what you call the power of a text.”</p>
<p>The book has been described as “exhilarating,” “luminous” and “unflinching, depicting those at the margins” of
Mormonism. “A lapsed Catholic,” writes poet Nancy Takacs, “I feel that any Mormon or other person raised with strict faith, will love these stories as well as non-religious readers curious about the secret lives of the Mormon faithful, and unfaithful. I could not put this book down.”</p>
<hr/>
<p>I really enjoy reading fiction by David G. Pace. He often captures the conflict between traditional Mormonism, its cultural comfort level, and inevitable questioning and repudiation of mores necessary in a changing world. In Pace’s work, this conflict, if continued, can irreparably damage a marriage, cause a general authority to want to rebel, or lead one of the Three Nephites to be fed up with Christ for giving him a never-ending gospel calling. <a href="https://www.associationmormonletters.org/reviews/older-reviews/pace-american-trinity-and-other-stories-from-the-mormon-corridor-reviewed-by-doug-gibson/"><b>Read more</b></a></p>
<hr/>
<p>David Pace’s <i>American Trinity</i> is a striking collection of twelve short stories tied together by the common thread of Mormonism. The stories were written over the past several decades, and draw from his lifelong experiences with the church. <a href="https://mainstreetplaza.com/2024/09/13/on-american-trinity/"><b>Read more</b></a></p>
