<a href="http://signaturebookslibrary.org/?p=12551"><img class="floatleft" width="170" height="254" src="books/dmf/cover_med.png"/></a><p>In Our Lovely Deseret: Mormon Fictions (edited by Robert Raleigh) is a collection of thought-provoking short-stories about life in the American West and/or in Mormon culture. Here there's Mormonism in the air, but it's not always at center-stage.</p>

<p>Many of the stories in this collection explore troubled or changing relationships, with the characters' cultural background as the framing structure for other human experiences. This is true of Levi Peterson's contribution "Durfey Renews an Interest in Rodeo" as well as others such as "My Father Waltzing Home" by Jan Stucki, "Throwing the Bread" by Ron Carlson, "Not Quite Peru" by Lee Ann Mortensen, and "Badlands" by Joanna Brooks.</p>

<p>One that stands out in this category is the lyrical "Fidelity" by Kristen Rogers about a small-town woman gaining the trust of a stray dog: "My dad had a shoe repair shop, T.L. said. He used to say, See this sole? This sole has walked maybe two thousand miles but I bet you it's never been more than five, ten miles from right here."</p>

<p>Other stories in the collection deal specifically with Mormonism and the Mormon issues. Several explore the tension between one's daily experiences and one's Mormon expectations, especially regarding sexuality. This internal conflict is clearly spelled out in the story "Almond Milk" by Johnny Townsend, about a gay Mormon missionary who meets an openly gay couple in Rome.</p>

<p>Two of my favorites in the collection were studies in Mormon sexuality: "Love, Mormon Style" by Bob Bringhurst, and "Twinkie" by Gary Burgess. "Love, Mormon Style" is a tragicomic caricature of the Mormon fixation on chastity and marriage and of the painfully confused result on healthy, horny young singles. "Twinkie" is a more poignant portrait of the same confusion and turmoil, as a Mormon man living in Hong Kong tries to make sense of his feeling for a local prostitute as he also tries to deal with his familiar culture's alien-ness in his current surroundings.</p>

<p>This collection has a remarkable variety of styles, themes, and tones, from poetic to straight-forward, from comic to tragic, from spiritual to earthy. As the editor, Robert Raleigh, states in the introduction: "Mormonism may be a jumping off point (for an ever growing number of people around the world), but ultimately these are stories about living, with its infinite variety of experiences and attendant emotions."</p>

<p>In a similar vein, Raleigh states the following goal:</p>

<p>"There is a tendency within Mormon culture to see the world in terms of good and evil. You are either for or against the ever advancing Kingdom of God. Within Mormon culture, art can entertain, but it should also instruct and enlighten. There is a growing body of work, however, that doesn't fit these categories or purposes. It is not for or against, but it is about. It doesn't exactly instruct, though it often provokes feeling and thought. This the type of work I have attempted to gather together in this collection." <a href="http://lfab-uvm.blogspot.ch/2007/02/challenges-and-pleasures-of-mormon-lit.html"><b>Read more</b></a></p>
